// IMPORTANT: Replace this file with the one generated by FlutterFire CLI.
// Run: flutterfire configure
// This generates the correct firebase_options.dart for your Firebase project.
//
// Installation: dart pub global activate flutterfire_cli
//               flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️  REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIGURATION VALUES
  // Get these from: Firebase Console > Project Settings > Your Apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:570417219974:web:e8aa5b0be25adb706ec407',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'chat-e171f',
    authDomain: 'chat-e171f.firebaseapp.com',
    storageBucket: 'chat-e171f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:570417219974:android:4d46e7a90b59303c6ec407',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'chat-e171f',
    storageBucket: 'chat-e171f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:570417219974:ios:e2be58eb0c7dc7bd6ec407',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'chat-e171f',
    storageBucket: 'chat-e171f.appspot.com',
    iosBundleId: 'com.example.secureChat',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'YOUR_MACOS_API_KEY',
  //   appId: 'YOUR_MACOS_APP_ID',
  //   messagingSenderId: 'YOUR_SENDER_ID',
  //   projectId: 'chat-e171f',
  //   storageBucket: 'chat-e171f.appspot.com',
  //   iosBundleId: 'com.example.secureChat',
  // );
}
